services:
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
        
  metadata-and-asset-management-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5000:80"
      - "50000:50001"

  metadata-and-asset-management-service-dapr:
    command: [ "./daprd",
               "-app-id", "metadata-and-asset-management-service",
               "-app-port", "80",
               "-components-path", "/components"
    ]
    volumes:
      - ./infrastructure/components:/components
  
  mock-producers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "6000:80"
      - "60001:50001"

  mock-producers-dapr:
    command: [ "./daprd",
               "-app-id", "mock-producers",
               "-app-port", "80",
               "-components-path", "/components"
    ]
    volumes:
      - ./infrastructure/components:/components
