@ContentRelay_MAM_Web_HostAddress = http://localhost:5000

@id = ASSET001

GET {{ContentRelay_MAM_Web_HostAddress}}/assetmetadata/{{id}}/
Accept: application/json

###

POST {{ContentRelay_MAM_Web_HostAddress}}/metadata/